name: Deploy Lambda
on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
      - uses: actions/checkout@v1
      - run: zip lambda.zip file.txt
      - uses: yvesgurcan/deploy-lambda-function
        with:
          package: lambda.zip index.js package.json node_modules
          function-name: getThumbnail
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
